config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [:index]

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :title, presence: true

  has_many :shoes
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  validates :name,          presence: true
  validates :shoe_code,     presence: true
  validates :price,         presence: true
  validates :price,         numericality: { greater_than_or_equal_to: 0 }, allow_blank: true


  belongs_to :brand

  has_attached_file :image, default_url: "/assets/shoes/nike_flex.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.find_by_brand_ids(brand_ids)
    where(brand: brand_ids)
  end

  def self.find_by_price_from(price_from)
    where('price >= ?', price_from )
  end

  def self.find_by_price_to(price_to)
    where('price <= ?', price_to )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shoe_filter = ShoeFilter.new(shoe_filter_params)
    @shoes = @shoe_filter.result.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  protected

  def shoe_filter_params
    params[:shoe_filter]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paginate(collection, params= {})
    will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)
  end
end

app/helpers/remote_link_pagination_helper.rb
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

app/views/home/_filter.html.slim
.home-filter-container
  label Refine by
  = simple_form_for ShoeFilter.new(params[:shoe_filter]), url: home_index_path, html: { method: :get }, remote: true do |f|
    h1 Brands
    = f.collection_check_boxes :brand_ids, Brand.all.map{ |b| [b.id, b.title]}, :first, :last
    h1 Price
    #price_bar
    = f.input :price_from, as: :hidden
    = f.input :price_to, as: :hidden

coffee:
  $('#new_shoe_filter input').change ->
    $(this).submit()

javascript:
  var price_bar = document.getElementById('price_bar');
  noUiSlider.create(price_bar, {
    start: [0, 200],
    connect: true,
    step: 50,
    range: {
      'min': 0,
      'max': 200
    },
    format: wNumb({
      decimals: 0
    })
  });
  price_bar.noUiSlider.on('change', function( values, handle ) {
    $('#shoe_filter_price_from').val(values[0])
    $('#shoe_filter_price_to').val(values[1])

    $('#new_shoe_filter').submit();
  });

  price_bar.noUiSlider.on('update', function( values, handle ) {
    $('#shoe_filter_price_from').val(values[0])
    $('#shoe_filter_price_to').val(values[1])
  });

app/views/home/_shoes.html.slim
.home-shoes-container
  span.count #{ @shoes.count } matching products
  span.sort
  .shoes
    - shoes.each do |shoe|
      .col.s4
        .item
          .image
            = image_tag(shoe.image)
          p.title = shoe.name
          p.code = shoe.shoe_code
          p.price $#{shoe.price}
          .card
            a class="waves-effect waves-light btn"
              i class="fa fa-shopping-cart" 
              | Add to card

app/views/home/index.html.slim
#home-index-container.container
  .row
    .col.l3
      = render 'home/filter'
    .col.l9
      = render 'shared/banner'
      #results
        = render partial: 'home/shoes', locals: { shoes: @shoes }
      = render partial: 'shared/pagination', locals: { shoes: @shoes }

app/views/home/index.js.erb
$("#results").html("<%= j render partial: 'home/shoes', locals: { shoes: @shoes } %>");

app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsTest8
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    header
      = render "shared/header"
      = render "shared/menu"
    main
      = yield
    footer
      = render "shared/footer"

app/views/shared/_banner.html.slim
.shared-banner-container
  = image_tag('banner.jpg')

app/views/shared/_footer.html.slim
.shared-footer-container
  = image_tag('footer.png')

app/views/shared/_header.html.slim
.shared-header-container.container
  .row
    .col.s1
      = image_tag('logo.jpg')

app/views/shared/_menu.html.slim
.shared-menu-container
  .row
    = image_tag('menu.png')

app/views/shared/_pagination.html.slim
.shared-pagination-container
  = paginate shoes